version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sns,s3,sts
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./tmp/localstack:/var/lib/localstack"
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
