export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const IMAGE_STORAGE_PORT = Symbol('IMAGE_STORAGE_PORT');
export const ORDER_NOTIFICATION_PORT = Symbol('ORDER_NOTIFICATION_PORT');

